version: 2
updates:
  - package-ecosystem: maven
    directory: /stacks/java-selenium-testng
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /stacks/python-playwright
    schedule:
      interval: weekly
