services:
  selenium-hub:
    image: selenium/hub:4.37.0-20251020@sha256:022b35f085df0c5f324d5da15e66c7e4971049d7606fb4293a802c9d4f77997b
    ports:
      - "4442-4444:4442-4444"
    environment:
      SE_SESSION_RETRY_INTERVAL: "1"
      SE_VNC_NO_PASSWORD: "1"

  chrome:
    image: selenium/node-chrome:4.37.0-20251020@sha256:17e719a9db3420ded324ea0bdfaaf1578e1a20ff4b6237330f8542177177cde1
    shm_size: 2gb
    depends_on:
      - selenium-hub
    volumes:
      - ../stacks/java-selenium-testng/target:/home/seluser/Downloads
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
      SE_NODE_ENABLE_MANAGED_DOWNLOADS: "true"
      SE_NODE_MAX_SESSIONS: "1"

  firefox:
    image: selenium/node-firefox:4.37.0-20251020@sha256:92aa8ad9544e3df24fa31e5dcf2b6fd90455f23c2365ac5232e1b934ca62d8c7
    shm_size: 2gb
    depends_on:
      - selenium-hub
    volumes:
      - ../stacks/java-selenium-testng/target:/home/seluser/Downloads
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
      SE_NODE_ENABLE_MANAGED_DOWNLOADS: "true"
      SE_NODE_MAX_SESSIONS: "1"

  edge:
    image: selenium/node-edge:4.37.0-20251020@sha256:9c85afa973372761c17605d8f8e8fe4c35eab7dcbe7312218177fc82db1f3c54
    shm_size: 2gb
    depends_on:
      - selenium-hub
    volumes:
      - ../stacks/java-selenium-testng/target:/home/seluser/Downloads
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
      SE_NODE_ENABLE_MANAGED_DOWNLOADS: "true"
      SE_NODE_MAX_SESSIONS: "1"
