#!/usr/bin/env python3
from __future__ import annotations

import argparse, difflib, re, sys
from pathlib import Path
from typing import cast

CATALOG = Path("scenarios/catalog.yml")
JAVA = Path("stacks/java-selenium-testng/src/test/java/theinternetwebsite/ui/testcases")
TS = Path("stacks/ts-playwright/tests")
PY = Path("stacks/python-playwright/tests")
MATRIX = Path("docs/scenario-matrix.md")
README = Path("README.md")
STACKS = ("java-selenium-testng", "ts-playwright", "python-playwright")
SCENARIO_ID = r"(?:UI|HTTP)-[A-Z0-9-]+"
# Each stack must carry the scenario ID somewhere that means "this test is this
# scenario", not merely somewhere in the file. Matching the ID anywhere would let
# a mention in a comment stand in for a test.
JAVA_PATTERNS = (rf'testName\s*=\s*"({SCENARIO_ID})"',)
TS_PATTERNS = (rf"\btest(?:\.\w+)*\(\s*['\"`]\s*({SCENARIO_ID})\b",)
PY_PATTERNS = (
    rf'"""\s*({SCENARIO_ID})\b',
    rf'@pytest\.mark\.\w+\(\s*[\'"]\s*({SCENARIO_ID})\b',
    rf'parametrize\([^)]*[\'"]\s*({SCENARIO_ID})\b',
)
HEADER = "| ID | Priority | Scenario | Java | TS | Python |"
SEPARATOR = "| --- | --- | --- | --- | --- | --- |"

def catalog() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for line in CATALOG.read_text().splitlines():
        s = line.strip()
        if s.startswith("- id: "):
            rows.append({"id": s[6:]})
        elif rows and s.startswith(("title: ", "priority: ")):
            key, val = s.split(": ", 1); rows[-1][key] = val
        elif rows and s.startswith("coverage: {"):
            rows[-1]["coverage"] = dict(re.findall(r"([\w-]+): (true|false)", s))
    return rows

def coverage(row: dict[str, object]) -> dict[str, str]:
    return cast(dict[str, str], row["coverage"])

def ids(root: Path, glob: str, patterns: tuple[str, ...]) -> set[str]:
    if not root.exists(): return set()
    text = "\n".join(p.read_text() for p in root.glob(glob))
    found: set[str] = set()
    for pattern in patterns: found |= set(re.findall(pattern, text))
    return found

def java_ids() -> set[str]:
    return ids(JAVA, "*.java", JAVA_PATTERNS)

def ts_ids() -> set[str]:
    return ids(TS, "**/*.ts", TS_PATTERNS)

def py_ids() -> set[str]:
    return ids(PY, "**/*.py", PY_PATTERNS)

def check(rows: list[dict[str, object]]) -> None:
    ids = [str(r["id"]) for r in rows]; all_ids = set(ids); java_tests = java_ids(); ts_tests = ts_ids(); py_tests = py_ids()
    java_catalog = {str(r["id"]) for r in rows if coverage(r)["java-selenium-testng"] == "true"}
    ts_catalog = {str(r["id"]) for r in rows if coverage(r)["ts-playwright"] == "true"}
    py_catalog = {str(r["id"]) for r in rows if coverage(r)["python-playwright"] == "true"}
    errors = []
    errors += [f"duplicate catalog ids: {sorted({i for i in ids if ids.count(i) > 1})}"] if len(ids) != len(all_ids) else []
    errors += [f"catalog java ids missing tests: {sorted(java_catalog - java_tests)}"] if java_catalog - java_tests else []
    errors += [f"java test ids missing catalog rows: {sorted(java_tests - all_ids)}"] if java_tests - all_ids else []
    errors += [f"java test ids not marked covered: {sorted(java_tests - java_catalog)}"] if java_tests - java_catalog else []
    errors += [f"catalog ts ids missing tests: {sorted(ts_catalog - ts_tests)}"] if ts_catalog - ts_tests else []
    errors += [f"ts test ids missing catalog rows: {sorted(ts_tests - all_ids)}"] if ts_tests - all_ids else []
    errors += [f"ts test ids not marked covered: {sorted(ts_tests - ts_catalog)}"] if ts_tests - ts_catalog else []
    errors += [f"catalog py ids missing tests: {sorted(py_catalog - py_tests)}"] if py_catalog - py_tests else []
    errors += [f"py test ids missing catalog rows: {sorted(py_tests - all_ids)}"] if py_tests - all_ids else []
    errors += [f"py test ids not marked covered: {sorted(py_tests - py_catalog)}"] if py_tests - py_catalog else []
    if errors: sys.exit("\n".join(errors))

def table(rows: list[dict[str, object]]) -> list[str]:
    out = [HEADER, SEPARATOR]
    for r in rows:
        c = coverage(r); marks = ["✅" if c[s] == "true" else "—" for s in STACKS]
        out.append(f"| {r['id']} | {r['priority']} | {r['title']} | {marks[0]} | {marks[1]} | {marks[2]} |")
    return out

MARKER = "<!-- GENERATED FILE — do not edit; run: python3 tools/check-scenarios.py --write-matrix -->"
LEGEND = "Legend: ✅ = covered by that stack · — = not covered."

def write_matrix(rows: list[dict[str, object]]) -> None:
    out = ["# Scenario coverage matrix", "", MARKER, "", "Generated by `tools/check-scenarios.py --write-matrix`.", "", LEGEND, ""] + table(rows)
    MATRIX.parent.mkdir(exist_ok=True); MATRIX.write_text("\n".join(out) + "\n")

def check_readme(rows: list[dict[str, object]]) -> None:
    lines = README.read_text().splitlines()
    if HEADER not in lines:
        sys.exit(f"{README}: scenario-matrix embed not found; expected a table headed\n  {HEADER}")
    start = lines.index(HEADER); end = start
    while end < len(lines) and lines[end].startswith("|"): end += 1
    embedded = lines[start:end]; expected = table(rows)
    if embedded != expected:
        diff = "\n".join(difflib.unified_diff(embedded, expected, f"{README} (embedded copy)", f"generated from {CATALOG}", lineterm=""))
        sys.exit(f"{README} scenario-matrix embed does not match the catalog:\n{diff}\n\nfix: copy the table out of {MATRIX} into the scenario-matrix section of {README}")

parser = argparse.ArgumentParser(); parser.add_argument("--write-matrix", action="store_true")
args = parser.parse_args(); rows = catalog(); check(rows)
if args.write_matrix: write_matrix(rows)
check_readme(rows)
print(f"scenario catalog ok: {len(rows)} rows, {len(java_ids())} java tests, {len(ts_ids())} ts tests, {len(py_ids())} py tests; readme embed in sync")
