#!/usr/bin/env python3
from __future__ import annotations

import argparse, re, sys
from pathlib import Path

CATALOG = Path("scenarios/catalog.yml")
JAVA = Path("stacks/java-selenium-testng/src/test/java/theinternetwebsite/ui/testcases")
MATRIX = Path("docs/scenario-matrix.md")
STACKS = ("java-selenium-testng", "ts-playwright", "python-playwright")

def catalog() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for line in CATALOG.read_text().splitlines():
        s = line.strip()
        if s.startswith("- id: "):
            rows.append({"id": s[6:]})
        elif rows and s.startswith(("title: ", "priority: ")):
            key, val = s.split(": ", 1); rows[-1][key] = val
        elif rows and s.startswith("coverage: {"):
            rows[-1]["coverage"] = dict(re.findall(r"([\w-]+): (true|false)", s))
    return rows

def java_ids() -> set[str]:
    text = "\n".join(p.read_text() for p in JAVA.glob("*.java"))
    return set(re.findall(r'testName\s*=\s*"([A-Z0-9-]+)"', text))

def check(rows: list[dict[str, object]]) -> None:
    ids = [str(r["id"]) for r in rows]; all_ids = set(ids); tests = java_ids()
    java_catalog = {str(r["id"]) for r in rows if dict(r["coverage"])["java-selenium-testng"] == "true"}
    errors = []
    errors += [f"duplicate catalog ids: {sorted({i for i in ids if ids.count(i) > 1})}"] if len(ids) != len(all_ids) else []
    errors += [f"catalog java ids missing tests: {sorted(java_catalog - tests)}"] if java_catalog - tests else []
    errors += [f"java test ids missing catalog rows: {sorted(tests - all_ids)}"] if tests - all_ids else []
    errors += [f"java test ids not marked covered: {sorted(tests - java_catalog)}"] if tests - java_catalog else []
    if errors: sys.exit("\n".join(errors))

def write_matrix(rows: list[dict[str, object]]) -> None:
    out = ["# Scenario coverage matrix", "", "Generated by `tools/check-scenarios.py --write-matrix`.", "", "| ID | Priority | Scenario | Java | TS | Python |", "| --- | --- | --- | --- | --- | --- |"]
    for r in rows:
        c = dict(r["coverage"]); marks = ["✅" if c[s] == "true" else "—" for s in STACKS]
        out.append(f"| {r['id']} | {r['priority']} | {r['title']} | {marks[0]} | {marks[1]} | {marks[2]} |")
    MATRIX.parent.mkdir(exist_ok=True); MATRIX.write_text("\n".join(out) + "\n")

parser = argparse.ArgumentParser(); parser.add_argument("--write-matrix", action="store_true")
args = parser.parse_args(); rows = catalog(); check(rows)
if args.write_matrix: write_matrix(rows)
print(f"scenario catalog ok: {len(rows)} rows, {len(java_ids())} java tests")
